<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $escaper \Magento\Framework\Escaper */
/** @var $configProvider \Magento\Search\ViewModel\ConfigProvider */
$configProvider = $block->getData('configProvider');
/** @var $helper \Magento\Search\Helper\Data */
$helper = $configProvider->getSearchHelperData();
$allowedSuggestion = $configProvider->isSuggestionsAllowed();
$quickSearchUrl = $allowedSuggestion ? $escaper->escapeUrl($helper->getSuggestUrl()) : '';
?>
<div class="search-box">
   <div class="widget  widget_product_search">
        <span class="search-icon">  </span>
        <form class="form minisearch woocommerce-product-search active" id="search_mini_form"
                action="<?= $escaper->escapeUrl($helper->getResultUrl()) ?>" method="get">
            <label class="label" for="search" data-role="minisearch-label">
                <span><?= $escaper->escapeHtml(__('What are you looking for?')) ?></span>
            </label>
            <input id="search"
                    data-mage-init='{
                    "quickSearch": {
                        "formSelector": "#search_mini_form",
                        "url": "<?= /* @noEscape */ $quickSearchUrl ?>",
                        "destinationSelector": "#search_autocomplete",
                        "minSearchLength": "<?= $escaper->escapeHtml($helper->getMinQueryLength()) ?>"
                    }
                }'
                    type="text"
                    name="<?= $escaper->escapeHtmlAttr($helper->getQueryParamName()) ?>"
                    value="<?= /* @noEscape */ $helper->getEscapedQueryText() ?>"
                    placeholder="<?= $escaper->escapeHtmlAttr(__('What are you looking for?')) ?>"
                    class="input-text search-field"
                    maxlength="<?= $escaper->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
                    role="combobox"
                    aria-haspopup="false"
                    aria-autocomplete="both"
                    autocomplete="off"
                    aria-expanded="false"/>
            <div id="search_autocomplete" class="search-autocomplete"></div>
            <div class="actions">
                <button type="submit"
                        title="<?= $escaper->escapeHtml(__('Search')) ?>"
                        class="action search"
                        aria-label="Search"
                >
                    <img src="<?php echo $block->getViewFileUrl('images/search_icon.png'); ?>" alt="MeetArts">
                </button>
            </div>
        </form>
    </div>
</div>
