<div class="footer-main ">
   <div class="footer content">
      <div class="footer-top-main ">
         <div class="container">
            <div class="footer-links-main">
				<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-links')->toHtml(); ?>
				<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-community-text')->toHtml(); ?>
				<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-newsletter')->toHtml(); ?>
            </div>
         </div>
         <div class="footer-bottom-main ">
            <div class="container">
               <div class="copy-written-text">
                  <div class="displa-fx">
                     <p> © <?= date('Y'); ?> <?php echo $this->getChildHtml("copyright"); ?> </p>
                  </div>
                  <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-social')->toHtml(); ?>
               </div>
            </div>
         </div>
      </div>
   </div>
   <a id="back2Top" title="Back to top" href="#" style="display: none;">
   <i class="fas fa-angle-up"></i>
   </a>
</div>
