<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit)
?>

<ul class="nav-mobile">
    <?= /* @noEscape */ $_menuHtml?>
    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('main-menu-extra-links')->toHtml(); ?>
    <?= $block->getChildHtml() ?>
</ul>
