<?php
/**
 * Webkul Software
 *
 * @category  Webkul
 * @package   Webkul_TwoFactorAuth
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

/** @var $viewModel \Webkul\TwoFactorAuth\ViewModel\HelperViewModel */
$viewModel = $block->getViewModel();
$jsonHelper = $viewModel->helper(\Magento\Framework\Json\Helper\Data::class);
$twoFactorHelper = $viewModel->helper(\Webkul\TwoFactorAuth\Helper\Data::class);
$twoFactorModalConfig = $twoFactorHelper->getOtpModalConfig();
$customerHelper = $viewModel->helper(\Webkul\TwoFactorAuth\Helper\Customer::class);

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php if($this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('login-2fa-content')->toHtml()): ?>
<div class="login-2fa-content">
    <div class="content">
        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('login-2fa-content')->toHtml(); ?>
    </div>
</div>
<script>
require(["jquery"],function(e){
    jQuery(document).ready(function() {
    });
});
</script>
<?php endif; ?>
<div class="block block-customer-login">
    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2">
            <?= $block->escapeHtml(__('Registered Customers')) ?>
        </strong>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading"
    data-mage-init=
    '{"Webkul_TwoFactorAuth/js/login": <?= /** @noEscape */ $jsonHelper->jsonEncode($twoFactorModalConfig) ?>}'>
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                <div class="field note">
                    <?= $block->escapeHtml(__('If you have an account, sign in with your email address.')) ?>
                </div>
                <div class="field email required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>"
                        <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
                        id="email" type="email" class="input-text"
                        title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}'
                        data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input name="login[password]" type="password"
                        <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
                        class="input-text" id="pass"
                        title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit" class="action login primary" name="send" id="send2">
                            <span><?= $block->escapeHtml(__('Sign In')) ?></span>
                        </button>
                    </div>
                    <div class="secondary">
                        <a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>">
                            <span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span>
                        </a>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>

