<?php
/**
 * Webkul Software
 *
 * @category  Webkul
 * @package   Webkul_TwoFactorAuth
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$loginReferrerUrl = $block->getLoginReferrerUrl();
$currentUrl = $block->getCurrentUrl();
$findLogin   = 'customer/account/login';
$isLoginUrl = strpos(strtolower($currentUrl), $findLogin);
?>
<script type="text/x-magento-init">
    {
        "*": {
            "resendAuthCode": {
                "loginReferrerUrl" : "<?= /* @noEscape */ $loginReferrerUrl ?>",
                "isLoginUrl" : <?= /* @noEscape */ $isLoginUrl ?: 0 ?>
            }
        }
    }
</script>