<?php
   /**
    * Webkul Software
    *
    * @category  Webkul
    * @package   Webkul_TwoFactorAuth
    * @author    Webkul Software Private Limited
    * @copyright Webkul Software Private Limited (https://webkul.com)
    * @license   https://store.webkul.com/license.html
    */
?>
<style>
   .view-backupcodes{
   border:0px solid black;
   }
   .main-container{
   background-color:#FFFFFF;
   border: 1px solid black;
   border-radius:10px;
   padding:20px; 
   }
   .main-container .row h3{
   font-family: ui-monospace;
   }
   .main-container .row ul {
   columns: 2;
   -webkit-columns: 2;
   -moz-columns: 2;
   padding: 7px 244px 16px 288px;
   }
   .main-container .row ul li {
   list-style-type: none;
   font-size: large;
   font-weight: 500;   
   }
</style>
<?php if ($block->getcollection()->getSize() == 0) {?>
<form class="form form-edit-account"
   action="<?= $block->escapeUrl($block->getUrl('twofactorauth/account/generatecode')) ?>"
   method="post" id="form-validate"
   enctype="multipart/form-data"
   data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
   autocomplete="off">
   <fieldset class="fieldset info" style="float: left;">
      <?= $block->getBlockHtml('formkey') ?>
      <legend class="legend"><span><?= $block->escapeHtml(__('Generate backup codes')) ?></span></legend>
      <div class="actions-toolbar">
         <div class="primary">
            <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Save')) ?>">
            <span><?= $block->escapeHtml(__('Get backup codes')) ?></span>
            </button>
         </div>
      </div>
   </fieldset>
</form>
<?php } else { ?>
<div class="container view-backupcodes">
   <legend class="legend"><span><?= $block->escapeHtml(__('Your backup codes')) ?></span></legend>
   <div class="main-container" id="main-con">
      <div class="row">
         <h3>10 backup codes remaining</h3>
         
         <button style="float:right;margin-top: -38px;" class="back-delete">Delete</button>
         <hr>
         <ul>
            <?php foreach ($block->getcollection() as $backupcodes) { ?>
            <li><?= $block->escapeHtml($backupcodes->getBackupcode())?></li>
            <?php } ?>
         </ul>
         <hr>
      </div>
   </div>
</div>
<?php }  ?>
<script>
   require(['jquery','Magento_Ui/js/modal/alert'], function($,alert){
       $('.back-delete').click(function(e) {
           var urllink;
           e.preventDefault();
           let text = "Are you sure you want to delete these codes?";
           if (confirm(text) == true) {
               urllink = window.location.href.slice(0, -11) + '/delete';
               $.ajax({
                        url: urllink,
                        data: {
                            action: 'disable',
                        },
                        type: 'post',
                        dataType: 'json',
                        success: function(data) {
                            if (data.result == 'true') {
                                alert({
                                    title: 'Message Alert',
                                    content: "Codes Delete Successfully",
                                    actions: {
                                        always: function(){
                                            location.reload();
                                            }
                                        }
                                    });                   
                            }

                        }
                    });
              
           } else {
             location.reload();
           }
       });
   });
</script>