<?php
/**
 * @category   Webkul
 * @package    Webkul_TwoFactorAuth
 * @author     Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license    https://store.webkul.com/license.html
 */

 $serializedData = $block->getSerializedData();
?>
<script type="text/x-magento-init">
    {
        "*":{
            "subscribeUsers":<?= $block->escapeJsQuote($serializedData) ?>
        }
    }
</script>