<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
<div class="product-options-bottom">
    <div class="add-to-box clearfix">
        <?php if ($block->shouldRenderQuantity() && 1==2) :?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <div class="add-cart-ajax"> 
                <?php if($_product->getTypeId() != 'etickets'):?>
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action button tocart br-button"
                        id="product-addtocart-button" disabled>
                        <img src="<?php echo $block->getViewFileUrl('images/car2.png'); ?>" alt=""><span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
                <?php else: ?>
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr('Tickets') ?>"
                        class="action button tocart costume-banner"
                        id="product-addtocart-button" disabled>
                        <span><?= $block->escapeHtml('Tickets') ?></span>
                </button>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
