<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

 use Magento\Framework\App\Action\Action;

/**
 *
 * @var $block \Magento\Catalog\Block\Product\View\Description
 */
$_product = $block->getProduct();
$webkul_helper    = $this->helper(Webkul\Marketplace\Helper\Data::class);
$verz_helper    = $this->helper(Verz\Design\Helper\Data::class);
$type = 'widget-product-grid';
$image = 'new_products_content_widget_grid';
$blockProduct = $block->getLayout()->createBlock('Magento\CatalogWidget\Block\Product\ProductsList');
?>
<?php 
    $marketplaceProduct = $webkul_helper->getSellerProductDataByProductId($_product->getId());
    $sellerId = "";
    $sellerName = "";
    foreach ($marketplaceProduct as $value) {
        $sellerId = $value['seller_id'];
        $sellerName = $value['name'];
    }
?>
<?php if($sellerId): ?>
    <?php 
        $sellerProductsCollection = $verz_helper->getSellerProductCollection($sellerId, $_product->getId(),4);
        $sellerInfo = $webkul_helper->getSellerInfo($sellerId);
        $shopUrl = @$sellerInfo['shop_url'];
    ?>
    <?php if(count($sellerProductsCollection)>0): ?>
    <section class="other-collection psame50 mb50">
        <div class="title mb20">
            <h2 class="size30 themetext pb15 semi-text"> Other Works by Artist </h2>
        </div>
        <div class="row">
            <?php $i=0; foreach ($sellerProductsCollection as $_item): $i++; if($i>4)continue; ?>
                <div class="col-sm-3">
                    <div class="item">
                        <div class="product-item">
                            <div class="product-item-info">
                                <div class="product-item-photo">
                                    <div class="product-image-container">
                                        <div class="product-img-view">
                                            <a href="<?= $block->escapeUrl($blockProduct->getProductUrl($_item)) ?>" class="product-image-wrapper">
                                                <?= $blockProduct->getImage($_item, $image)->toHtml() ?>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <div class="product-item-details">
                                    <div class="prd-title">
                                        <a href="<?= $block->escapeUrl($blockProduct->getProductUrl($_item)) ?>" class="product-name-warpper"> 
                                            <span class="product-name"> <?= $block->escapeHtml($_item->getName()) ?> </span>
                                        </a>
                                        <?= $blockProduct->getProductPriceHtml($_item, $type) ?>
                                    </div>
                                    <?php if ($_item->isSaleable()): ?>
                                        <?php $postParams = $blockProduct->getAddToCartPostParams($_item); ?>
                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_item->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                            <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                            <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart">
                                                <img src="<?php echo $block->getViewFileUrl('images/car2.png'); ?>" alt="">
                                            </button>
                                        </form>
                                    <?php endif; ?>                                    
                                </div>
                            </div>
                        </div>	
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="center mt15">
            <a href="<?= $block->escapeUrl($block->getUrl('')) ?>marketplace/seller/profile/shop/<?= $shopUrl;?>" class="button custome-btn"> Browse More </a>
        </div>
    </section>
    <?php endif; ?>
<?php endif; ?>