<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog related posts template
 *
 * @var $block \Magefan\Blog\Block\Post\View\RelatedProducts
 */
$verz_helper    = $this->helper(Verz\Design\Helper\Data::class);
$webkul_helper    = $this->helper(Webkul\Marketplace\Helper\Data::class);
?>

<?php
if ($exist = $block->getItems()->getSize()) {
    $type = 'related';
    $class = $type;

    $image = 'related_products_list';
    $title = __('Related Products');
    $items = $block->getItems();
    $limit = 0;
    $shuffle = 0;
    $canItemsAddToCart = true;

    $showWishlist = true;
    $showCompare = true;
    $showCart = false;
    $templateType = null;
    $description = false;
}
?>

<?php if ($exist):?>

    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="mfblog-related-products-block block <?= $block->escapeHtml($class); ?>"
                 data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}'
                 data-limit="<?= $block->escapeHtml($limit); ?>"
                 data-shuffle="<?= $block->escapeHtml($shuffle); ?>">
        <?php else: ?>
            <div class="block <?= $block->escapeHtml($class); ?>"
                 data-mage-init='{"upsellProducts":{}}'
                 data-limit="<?= $block->escapeHtml($limit); ?>"
                 data-shuffle="<?= $block->escapeHtml($shuffle); ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block <?= $block->escapeHtml($class); ?>">
    <?php endif; ?>
    <div class="block-title title">
        <strong id="block-<?= $block->escapeHtml($class)?>-heading"
                role="heading"
                aria-level="2"><?= $block->escapeHtml($title); ?>
        </strong>
    </div>
    <div class="row">
        <?php $iterator = 1; ?>
        <?php foreach ($items as $_item): ?>
            <div class="col-sm-3">
                <div class="product-item-info ">
                    <div class="product-item-photo">
                        <div class="product-image-container">
                            <div class="product-img-view">
                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-image-wrapper">
                                    <?= $block->getImage($_item, $image)->toHtml(); ?>
                                </a>
                            </div>		
                        </div>	
                    </div>
                    <div class="product-item-details">
                        <div class="prd-title-wrps">
                            <h2 class="size20"> 
                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>">
                                    <?= $block->escapeHtml($_item->getName()) ?></a>
                                </a>
                            </h2>
                            <?php 
                                $marketplaceProduct = $webkul_helper->getSellerProductDataByProductId($_item->getId());
                                $sellerName = "";
                                foreach ($marketplaceProduct as $value) {
                                    $sellerName = $value['name'];
                                }
                                ?>
                            <span class="sub-title"><?= $sellerName; ?></span>
                        </div>
                        <?php if ($_item->isSaleable()): ?>
                            <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                <button class="action tocart"
                                        data-mage-init='{"redirectUrl": {"url": "<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}'
                                        type="button"
                                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>">
                                        <img src="<?php echo $block->getViewFileUrl('images/car2.png'); ?>" alt="">
                                </button>
                            <?php else: ?>
                                <?php $postDataHelper = $this->helper(Magento\Framework\Data\Helper\PostHelper::class);
                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()]);
                                ?>
                                <button class="action tocart"
                                        data-post='<?= $block->escapeHtml($postData); ?>'
                                        type="button" title="<?= $block->escapeHtml(__('Add to Cart')) ?>">
                                        <img src="<?php echo $block->getViewFileUrl('images/car2.png'); ?>" alt="">
                                </button>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        <?php endforeach ?>
    </div>
</div>
<?php endif;?>
