<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list template
 *
 * @var $block \Magefan\Blog\Block\Post\PostList
 */
?>
<?php
$_postCollection = $block->getPostCollection();
?>
<div class="blog-page-section">
<?php if (!$_postCollection->count()): ?>
    <div class="message info empty">
        <div>
            <?= $block->escapeHtml(__('We can\'t find posts matching the selection.')) ?>
        </div>
    </div>
<?php else: ?>
    <?= $block->getAdditionalHtml() ?>
    <div class="header-title">
        <h1 class="size45 themetext"> Blogs </h1>
        <?= $block->getToolbarHtml() ?>
    </div>
    <div class="event-page post-list-wrapper">
        <?php $iterator = 1; ?>
        <div class="row post-list">
            <?php foreach ($_postCollection as $_post): ?>
                <?= $block->getPostHtml($_post) ?>
            <?php endforeach; ?>
        </div>
        <?= $block->getToolbarHtml() ?>
    </div>
<?php endif; ?>
</div>
