<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */
?>
<?php $_product = $block->getProduct() ?>
<?php if ($block->displayProductStockStatus()) : ?>
    <?php if ($_product->isAvailable()) : ?>
        <div class="product-stock available">
            <span class="overview-label stock-label"><?= $block->escapeHtml(__('Availability')) ?> :</span>
            <span class="stock-avail"><?= $block->escapeHtml(__('In-Stock')) ?></span>
        </div>
    <?php else : ?>
        <div class="product-stock unavailable">
            <span class="overview-label stock-label"><?= $block->escapeHtml(__('Availability')) ?> :</span>
            <span class="stock-avail"><?= $block->escapeHtml(__('Out of stock')) ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
<?= $block->getChildHtml('bundle_prices') ?>
