<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpBuyerSellerChat
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<style type="text/css">
    <?php if ($block->getConfigData('background_type') == 'color'): ?>
    .chat .chat-history{
        background:<?= /* @noEscape */ $block->getConfigData('solid_color') ?>!important;
    }
    <?php elseif ($block->getConfigData('background_type') == 'image'): ?>
    .chat .chat-history{
        background: url(<?= /* @noEscape */ $block->getBackgroundImage() ?>)!important;
        background-size: cover;
        background-repeat: no-repeat;

    }
    <?php else: ?>
    .chat .chat-history{
        background: #fff;
    }
    <?php endif; ?>

    <?php if ($block->getConfigData('header_color')): ?>
    #chatbox-component header.chatbox-header{
        background:<?= /* @noEscape */ $block->getConfigData('header_color') ?>!important;
    }
    <?php else: ?>
    .#chatbox-component header.chatbox-header{
        background: #293239;
    }
    <?php endif; ?>

    <?php if ($block->getConfigData('header_text_color')): ?>
    #chatbox-component header.chatbox-header{
        color:<?= /* @noEscape */ $block->getConfigData('header_text_color') ?>!important;
    }
    <?php else: ?>
    .#chatbox-component header.chatbox-header{
        color: #fff;
    }
    <?php endif; ?>

    <?php if ($block->getConfigData('window_position') !== ''): ?>
    #chatbox-component{
        <?= /* @noEscape */ $block->getConfigData('window_position') ?>:24px!important;
    }
    <?php else: ?>
    .#chatbox-component{
        right: 24px!important;
    }
    <?php endif; ?>
    
</style>