<?php
/**
 * @var $block Magepow\InfiniteScroll\Block\InfiniteScroll
 */

$helper = $this->helper('Magepow\InfiniteScroll\Helper\Data');
$isEnabled      = $helper->getConfigModule('general/enabled');
$delay          = $helper->getConfigModule('general/delay');
$content        = $helper->getConfigModule('general/content');
$pagination     = $helper->getConfigModule('general/pagination');
$next           = $helper->getConfigModule('general/next');
$item           = $helper->getConfigModule('general/item');
$loadingText    = $helper->getConfigModule('general/loading_text');
$doneText       = $helper->getConfigModule('general/done_text');
$loadMore       = $helper->getConfigModule('general/load_more');
$loadMoreText   = $helper->getConfigModule('general/load_more_text');
$loadingImage   = $helper->getConfigModule('general/loading_image');
$imgPath        = 'magepow/infinitescroll/'. $loadingImage;
if ($loadingImage) {
    $loadingImage = $block->getMedia($imgPath);
} else {
    $loadingImage = $this->getViewFileUrl('images/loader-1.gif');
}
?>
<script type="text/javascript">
    require(['jquery', 'magepow/infinitescroll', 'catalogAddToCart',"matchHeight"], function ($) {
        $(document).on("click",".lof-cr-item",function (e) {
            e.preventDefault();
            window.location.href= $(this).data('href');
            return false;
        });
        "use strict";
        $(document).ready(function () {
            $('body').addClass('infinitescroll');
            if(jQuery().ias) {
                $.ias('destroy');
            }
            window.ias = $.ias({
                container: "<?=  $content ?>",
                item: "<?= $item ?>",
                pagination: "<?= $pagination ?>",
                next: "<?= $next ?>",
                delay: "<?= $delay ?>",
            });
            window.ias.extension(new IASSpinnerExtension({
                src: "<?= $loadingImage ?>",
                html: '<div class="iass-spinner center"><img src="{src}"/><span><?= $loadingText ?></span></div>'
            }));
            window.ias.extension(new IASNoneLeftExtension({
                text: "<?= $doneText ?>",
                html: '<div class="ias-noneleft">{text}</div>'
            }));
            window.ias.extension(new IASTriggerExtension({
                text: "<?= $loadMoreText ?>",
                html: '<div class="ias-trigger ias-trigger-next btn-wrp center mt10"><button class="load-more custome-btn"><?= $loadMoreText ?></button></div>',
                textPrev: "<?= $loadMoreText ?>",
                htmlPrev: '<div class="ias-trigger ias-trigger-prev btn-wrp center mt10"><button class="load-more custome-btn"><?= $loadMoreText ?></button></div>',
                offset: "<?= $loadMore ?>",
            }));
			
			
			
            window.ias.on('rendered', function (items) {
                $('body').trigger('contentUpdated');
                $("form[data-role='tocart-form']").catalogAddToCart();
                var highestBox = 0;
                jQuery('.product-item-info').each(function(){
					if(jQuery(this).outerHeight() > highestBox) {
						highestBox = parseInt(jQuery(this).outerHeight())+1; 
					}
				});
				// jQuery('.product-item-info').css("height", highestBox+"px");
            });
        });
    });
</script>
